title: Katrina Alcala
logo: /assets/img/ka_logo.jpg
description: Experienced engineer with a master's degree in computer science and a background in software engineering and testing within the FinTech and Telecom fields.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
